### Transforming Code Into Idiomatic Python
* Replace traditional index manupulation with Python core looping idiomatic

In [14]:
# Looping over a range of numbers - Traditional Approach
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [15]:
# Idotiomatic Programming
for i in range(6):
    print(i**2,end=" ")

0 1 4 9 16 25 

### Looping Over A Collection

In [16]:
colors=['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

red green yellow purple 

In [17]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

### Looping Backward

In [18]:
colors=['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [19]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red 

In [20]:
colors=['red','green','yellow','purple']
for color in sorted(colors):
    print(color,end=" ")

green purple red yellow 

In [21]:
colors=['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

###
     * if x<=y and y<=z:
     * if x<=y<=z:
     * if x==True:
     * if x:

## Pandas

In [22]:
import pandas as pd

In [25]:
dt={'Id':[11,12,13,14,15],
   'first_name':['A','B','C','D','E'],
   'company':['aa','bb','cc','dd','ee'],
   'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt=pd.DataFrame(dt)

In [26]:
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [27]:
import os

In [29]:
os.chdir('C:\\Desktop\\')  # Saves to certain Location

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Desktop\\'

In [31]:
mydt.to_csv('WorkingFile.csv',index=False)

In [32]:
pwd

'C:\\Users\\SYS-07\\Desktop\\PythonProgramming'

## Reading the data from CSV file:


In [33]:
mydata=pd.read_csv('WorkingFile.csv')

In [34]:
print(mydata)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [35]:
mydata1= pd.read_csv('WorkingFile.csv',skiprows=1,
                     names=['CustId','Name','Company','Address'])

In [36]:
print(mydata1)

   CustId Name Company Address
0      11    A      aa     Hyd
1      12    B      bb     Hyd
2      13    C      cc     Hyd
3      14    D      dd     Hyd
4      15    E      ee     Hyd



## Print Only Two Columns
## Print the large value from CustID column -- max
## Print the least value from CustID column -- min
## Average of CustID column -- sum(li)/len(li)

## Numpy Package

* Numpy arrays are bit like Python List
* Numpy is also one of data structures
* Numpy is short name for 'Numeric Python' or 'Numerical Python'

In [6]:
import numpy as np  # Import the numpy package

In [7]:
li=[1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [8]:
array=np.array(li)
print(array)   # Convert the list into array using np.array()

[1 2 3 4 5]


In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(2,3),(3,4)])
print(a2.shape)

(2, 3)
(3, 2)


In [14]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [17]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
